### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by YuqiHuai** [daohu527/seahorse#11]
Hi @daohu527 

I’m very interested in contributing to this project and I’ve wanted a python ADS for a long time. How should we contribute to this project?

**Comment by daohu527** [comment]
I will create a new plan and organize some discussions, **welcome to participate!** 

Yes, I feel some inconveniences with the current use of autonomous driving, so I want to make an autonomous driving system that is simple, **easy to use**, and has rich algorithms and interfaces.

I have just started this project. Of course, I actually have a lot of ideas. The most urgent thing at the moment is to perfect the perception part first.

I currently use pytorch to implement several functions such as object detection, segmentation, and posture detection. I hope that what you see is what you get.

![seahorse_architecture](https://github.com/daohu527/seahorse/assets/10419854/b3a6fa01-c4bd-4ce8-81fe-57961c85d2d1)

## input
For example you can specify the input source as:

- **Files**: txt (include path), pictures, videos, point clouds, bags
- **Network files**: URL
- **Stream**: video stream
- **Screenshot**: Screenshot
- **Messages**: subscribe topics

## output
After model inference, the visual interface can be directly output.
- Visualized results with labels
- Inference results save desired format

I hope it can implement various algorithm libraries as elegantly as possible. There are already some ideas for these, and I hope it is easy to simulate.
